### ISSUE TITLE
Task List 

### ISSUE THREAD

**Issue by AbnerVera** [AlmirFonseca/AnaliseArtistas#1]
- [ ] Código de Scrapping 
- [ ] Refactory do código de Scrapping 
- [ ] Organização e limpeza dos dados obtidos
- [ ] Análise dos dados
